version: '3.7'  # Adjust Compose version as needed

services:
  db1:
    image: mariadb:latest    
    ports: 
      - "8001:3306"
    environment:
      MARIADB_ROOT_PASSWORD: secret

  db2:
    image: mariadb:10
    ports:
      - "8002:3306"
    environment:
      MARIADB_ROOT_PASSWORD: secret
  
  netshoot:
    image: nicolaka/netshoot
    command: ["sleep", "3600"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
