apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app_name: myredis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app_name: myredis
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
        - containerPort: 80