apiVersion: v1
kind: Service
metadata:
  name: notjeff-selector-svc
spec:
  selector:
    conference: present
    tshirt : red 
    handed : right
    hair: black
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
