apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      svc1: svc1
      svc2: svc2
  template:
    metadata:
      labels:
        app: nginx
        svc1: svc1
        svc2: svc2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: cm2
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-homepages