apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      svc2: svc2
  template:
    metadata:
      labels:
        app: nginx
        svc2: svc2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: cm3
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-homepages