apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
spec:
  type: NodePort
  selector:
    app: nginx
    svc1: svc1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001