apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
spec:
  type: NodePort
  selector:
    app: nginx
    svc2: svc2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002