apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-10-23T21:14:48Z"
  generation: 1
  labels:
    app: noah-dep
  name: noah-dep
  namespace: default
  resourceVersion: "1920"
  uid: a2021e4b-9764-4d50-88bd-25cfd456ee75
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: noah-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: noah-dep
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports: 
          - containerPort: 80
        # command:
        #   - ls
        #   - "-l"
        #   - "/etc/secret-volume"
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
          - name: cm-nginx-config
            mountPath: "/etc/nginx/nginx.conf"
            subPath: config
          - name: cm-nginx-config
            mountPath: "/etc/nginx/sites-available/testwiit7501_derp.org.conf"
            subPath: test-sie
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: test-secret
      - name: cm-nginx-config
        configMap:
          name: test-nginx-cm

status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-10-23T21:14:49Z"
    lastUpdateTime: "2024-10-23T21:14:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-10-23T21:14:48Z"
    lastUpdateTime: "2024-10-23T21:14:49Z"
    message: ReplicaSet "noah-dep-5769cb4469" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
