apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"secret-dotfiles-pod","namespace":"default"},"spec":{"containers":[{"command":["ls","-l","/etc/secret-volume"],"image":"registry.k8s.io/busybox","name":"dotfile-test-container","volumeMounts":[{"mountPath":"/etc/secret-volume","name":"secret-volume","readOnly":true}]}],"volumes":[{"name":"secret-volume","secret":{"secretName":"dotfile-secret"}}]}}
  creationTimestamp: "2024-10-23T21:07:47Z"
  name: secret-dotfiles-pod
  namespace: default
  resourceVersion: "1874"
  uid: 530e3d16-1478-4a52-8c61-b917dd92faa0
spec:
  containers:
  - command:
    - ls
    - -l
    - /etc/secret-volume
    image: registry.k8s.io/busybox
    imagePullPolicy: Always
    name: dotfile-test-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/secret-volume
      name: secret-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8hdww
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-derp-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: secret-volume
    secret:
      defaultMode: 420
      secretName: dotfile-secret
  - name: kube-api-access-8hdww
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-23T21:07:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-10-23T21:07:47Z"
    message: 'containers with unready status: [dotfile-test-container]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-10-23T21:07:47Z"
    message: 'containers with unready status: [dotfile-test-container]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-10-23T21:07:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2c4db0573b9df13e31118442cfe89d1c0df6050dbf4abad42dcd84bb1ad4ce24
    image: registry.k8s.io/busybox:latest
    imageID: sha256:36a4dca0fe6fb2a5133dc11a6c8907a97aea122613fa3e98be033959a0821a1f
    lastState:
      terminated:
        containerID: containerd://2c4db0573b9df13e31118442cfe89d1c0df6050dbf4abad42dcd84bb1ad4ce24
        exitCode: 0
        finishedAt: "2024-10-23T21:13:39Z"
        reason: Completed
        startedAt: "2024-10-23T21:13:39Z"
    name: dotfile-test-container
    ready: false
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=dotfile-test-container
          pod=secret-dotfiles-pod_default(530e3d16-1478-4a52-8c61-b917dd92faa0)
        reason: CrashLoopBackOff
  hostIP: 192.168.96.3
  phase: Running
  podIP: 10.42.0.9
  podIPs:
  - ip: 10.42.0.9
  qosClass: BestEffort
  startTime: "2024-10-23T21:07:47Z"
