apiVersion: v1
kind: ConfigMap
metadata:
  name: test-nginx-cm
data:
  new_sie: |-
    server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;

      server_name testwiit7501_derp.org;
      set $base /var/www/testwiit7501_derp.org;
      root $base/public;

      # SSL
      ssl_certificate /etc/letsencrypt/live/testwiit7501_derp.org/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/testwiit7501_derp.org/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/testwiit7501_derp.org/chain.pem;

      # security
      include nginxconfig.io/security.conf;

      # index.php
      index index.php;

      # index.php fallback
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      # handle .php
      location ~ \.php$ {
        include nginxconfig.io/php_fastcgi.conf;
      }

      # additional config
      include nginxconfig.io/general.conf;
    }

    # subdomains redirect
    server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;

      server_name *.testwiit7501_derp.org;

      # SSL
      ssl_certificate /etc/letsencrypt/live/testwiit7501_derp.org/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/testwiit7501_derp.org/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/testwiit7501_derp.org/chain.pem;

      return 301 https://testwiit7501_derp.org$request_uri;
    }

    # HTTP redirect
    server {
      listen 80;
      listen [::]:80;

      server_name .testwiit7501_derp.org;

      include nginxconfig.io/letsencrypt.conf;

      location / {
        return 301 https://testwiit7501_derp.org$request_uri;
      }
    }
  config: |-
    # Created by Noah, Eric, Gerardo, and Bill
    # Generated by nginxconfig.io
    # https://www.serverion.com/nginx-config/#?0.domain=testwiit7501_derp.org&client_max_body_size=32

    user www-data;
    pid /run/nginx.pid;
    worker_processes auto;
    worker_rlimit_nofile 65535;

    events {
      multi_accept on;
      worker_connections 65535;
    }

    http {
      charset utf-8;
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      server_tokens off;
      log_not_found off;
      types_hash_max_size 2048;
      client_max_body_size 32M;

      # MIME
      include mime.types;
      default_type application/octet-stream;

      # logging
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log warn;

      # SSL
      ssl_session_timeout 1d;
      ssl_session_cache shared:SSL:10m;
      ssl_session_tickets off;

      # Diffie-Hellman parameter for DHE ciphersuites
      ssl_dhparam /etc/nginx/dhparam.pem;

      # Mozilla Intermediate configuration
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

      # OCSP Stapling
      ssl_stapling on;
      ssl_stapling_verify on;
      resolver 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
      resolver_timeout 2s;

      # load configs
      include /etc/nginx/conf.d/*.conf;
      include /etc/nginx/sites-enabled/*;
    }